[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "property"
version = "0.1.0"
requires-python = "~=3.12"
dependencies = [
    "ase~=3.24",
    "pymatgen==2025.3.10",
    "matgl==1.2.1",
]
